### ISSUE TITLE
Error running URLCrazy

### ISSUE THREAD

**Issue by CybernetiX-S3C** [urbanadventurer/urlcrazy#1]
/usr/share/urlcrazy/tld.rb:81: warning: key "2nd_level_registration" is duplicated and overwritten on line 81
/usr/share/urlcrazy/tld.rb:89: warning: key "2nd_level_registration" is duplicated and overwritten on line 89
/usr/share/urlcrazy/tld.rb:91: warning: key "2nd_level_registration" is duplicated and overwritten on line 91

**Comment by urbanadventurer** [comment]
Thanks for reporting this issue @CybernetiX-S3C. This has been fixed in version 0.6.
