### ISSUE TITLE
Missing wrong TLD

### ISSUE THREAD

**Issue by fenderstrato666** [urbanadventurer/urlcrazy#2]
If you run Urlcrazy on google.com, only 16 wrong tld's is listed, even that for instance, google.in exists, and potentially more TLD's and is not returned in the output. Google is just an examle as i have seen similar issue on another .com domain. Any good ideas why?

**Comment by urbanadventurer** [comment]
Expanding the TLDs is a good idea, and is planned for future versions of URLCrazy.

**Comment by urbanadventurer** [comment]
This is now implemented 😎

**Comment by fenderstrato666** [comment]
Thx for this :-)
