### ISSUE TITLE
Invalid domain name against ".co" domain

### ISSUE THREAD

**Issue by altjx** [urbanadventurer/urlcrazy#3]
Hi there,

Just pulled the latest version of urlcrazy down and tested it against a domain that ends in `.co`. However, it looks like it's not being detected as a valid domain

**Comment by urbanadventurer** [comment]
OK, I've found the problem and fixed it. The TLD was out-dated and thought 2nd level registration for .co was invalid.

`=> {"type"=>"country", "tld"=>"co", "2nd_level_registration"=>**true**, "foreign_registration"=>false, "country"=>"Colombia", "slds"=>["com.co", "org.co", "edu.co", "gov.co", "net.co", "mil.co", "nom.co"]}`
