### ISSUE TITLE
Cannot output file

### ISSUE THREAD

**Issue by chrisnelmeskirkiss** [urbanadventurer/urlcrazy#6]
On Kali 2020.3, unable to output files from URLCrazy.

urlcrazy -o ~/Desktop/urlcrazy-human test.com

or urlcrazy -o test.txt test.com

user@kali:~$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]

both complete okay but no file created. Tested also on Ubuntu 16.10 on Ruby 2.5.5 same issue, with URLCrazy 0.7.1 and 0.6

Regards
Chris

**Comment by urbanadventurer** [comment]
Thanks @chrisnelmeskirkiss. I've fixed this in the new release v0.7.2
